name: forma_gallery
description: Forma Design System — gallery & docs showcase (custom, no Widgetbook).
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  forma_core: ^2.0.2
  forma_theme_plantao_facil: ^2.0.1
  forma_theme_dominus: ^2.0.1
  forma_theme_spooliq: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
